# Generated by Django 5.1.8 on 2025-04-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_paying_paid_course_paying_paid_lesson"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
